apiVersion: networking.k8s.io/v1 

kind: Ingress 

metadata: 

  name: my-ingress

  namespace: prod  

  annotations: 

    nginx.ingress.kubernetes.io/rewrite-target: / 

spec: 

  ingressClassName: nginx 

  rules: 

    - host: a3f99f0f9ba724900b4655e0d4765cee-669708618.ap-south-1.elb.amazonaws.com

      http: 

        paths: 

          - path: / 

            pathType: Prefix 

            backend: 

              service: 

                name: app-service

                port: 

                  number: 80 
