apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: prod
type: Opaque
data:
  DB_NAME: YXBwZGI=
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=
  DB_HOST: bXlhcHAtZGIuYzEyMndrODJtczQuYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==